# Generated by Django 3.2.23 on 2023-11-28 11:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Rubrik')),
                ('event_date', models.DateField(verbose_name='Datum')),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Bild')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Utkast'), (1, 'Publicera')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['created_on'],
            },
        ),
    ]
