# Generated by Django 3.2.23 on 2023-12-05 14:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('event_date', models.DateField(verbose_name='Date')),
                ('event_description', models.TextField(default='Descripe the event here...', max_length=130)),
                ('event_location', models.CharField(default='Exampleway 123, 456 78, City', max_length=50)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Image')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['created_on'],
            },
        ),
    ]
