# Generated by Django 3.2.23 on 2024-02-17 11:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='static/img/card-background.jpg', max_length=255, verbose_name='Image'),
        ),
    ]
