# Generated by Django 3.2.23 on 2023-11-28 13:21

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_post_signerat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Signerat',
        ),
        migrations.AddField(
            model_name='post',
            name='event_adress',
            field=models.CharField(default='Exampleway 123, 456 78, City', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='event_location',
            field=models.TextField(default='Descripe the event here...'),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
    ]
