# Generated by Django 3.2.23 on 2023-11-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20231128_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='event_adress',
        ),
        migrations.AddField(
            model_name='post',
            name='event_description',
            field=models.TextField(default='Descripe the event here...'),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_location',
            field=models.CharField(default='Exampleway 123, 456 78, City', max_length=150),
        ),
    ]
