# Generated by Django 3.2.23 on 2023-11-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20231110_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateField(verbose_name='Datum'),
        ),
    ]
