# Generated by Django 3.2.23 on 2024-02-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
