# Generated by Django 3.2.23 on 2023-12-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20231128_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_description',
            field=models.TextField(default='Descripe the event here...', max_length=130),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_location',
            field=models.CharField(default='Exampleway 123, 456 78, City', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Title'),
        ),
    ]
