# Generated by Django 3.2.23 on 2023-11-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_post_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
