# Generated by Django 3.2.23 on 2023-12-05 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('booking_location', models.TextField(max_length=250)),
                ('booking_created', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_email', to=settings.AUTH_USER_MODEL)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_fname', to=settings.AUTH_USER_MODEL)),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_lname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
